### ISSUE TITLE
Are dromedaries not camels?

### ISSUE THREAD

**Issue by andrwcrr** [DasBlackfur/actually-camel#1]
Source:
![image](https://github.com/DasBlackfur/actually-camel/assets/128940455/47b14235-201d-466d-85aa-07ed63aa3c41)

**Comment by JuceInUse** [comment]
Dromedaries **are** camels, you're right. I don't know why people insist that dromedaries aren't camels, it's a Reddit nitpick. I was gonna ask the same thing lol

**Comment by DasBlackfur** [comment]
Its not the thing I want and I am free to create this mod for whom feel like me.
